name: Deploy Canary Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CANARY_HOST }}
          username: ${{ secrets.CANARY_USERNAME }}
          password: ${{ secrets.CANARY_PASSWORD }}
          port: ${{ secrets.CANARY_PORT }}
          script: | 
            echo "[deploy.sh `date`]: Deploying Laravel Application."
            cd ${{ secrets.CANARY_PROJECT_PATH }}
            echo "[deploy.sh `date`]: Shutting site down."
            php artisan down
            echo "[deploy.sh `date`]: Pulling remote origin "
            git pull origin master
            echo "[deploy.sh `date`]: Installing composer dependencies."
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            echo "[deploy.sh `date`]: Linking storage directory."
            php artisan storage:link
            echo "[deploy.sh `date`]: Running migrations."
            php artisan migrate --force
            echo "[deploy.sh `date`]: Clearing cache."
            php artisan optimize:clear
            echo "[deploy.sh `date`]: Caching system files."
            php artisan optimize
            echo "[deploy.sh `date`]: Going live."
            php artisan up
            echo "[deploy.sh `date`]: Done."
